//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itog3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказ услуг.
    /// </summary>
    // *** Start programmer edit section *** (ОказУслуг CustomAttributes)

    // *** End programmer edit section *** (ОказУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("Оказ услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказУслугE", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсульт as \'Время консульт\'",
            "ПредостУслуга as \'Предост услуга\'",
            "ПереченьУслуг as \'Перечень услуг\'",
            "ПереченьУслуг.ЗатрВремя.Наименование"})]
    [MasterViewDefineAttribute("ОказУслугE", "ПереченьУслуг", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ОказУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fВремяКонсульт;
        
        private IIS.Itog3.Услуга fПредостУслуга;
        
        private IIS.Itog3.ПереченьУслуг fПереченьУслуг;
        
        private IIS.Itog3.Договор fДоговор;
        
        private IIS.Itog3.РасчетОстВрем fРасчетОстВрем;
        
        // *** Start programmer edit section *** (ОказУслуг CustomMembers)

        // *** End programmer edit section *** (ОказУслуг CustomMembers)

        
        /// <summary>
        /// ВремяКонсульт.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт CustomAttributes)
        public virtual int ВремяКонсульт
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Get start)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Get start)
                int result = this.fВремяКонсульт;
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Get end)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Set start)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Set start)
                this.fВремяКонсульт = value;
                // *** Start programmer edit section *** (ОказУслуг.ВремяКонсульт Set end)

                // *** End programmer edit section *** (ОказУслуг.ВремяКонсульт Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.Дата CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.Дата Get start)

                // *** End programmer edit section *** (ОказУслуг.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОказУслуг.Дата Get end)

                // *** End programmer edit section *** (ОказУслуг.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.Дата Set start)

                // *** End programmer edit section *** (ОказУслуг.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОказУслуг.Дата Set end)

                // *** End programmer edit section *** (ОказУслуг.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПредостУслуга.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.ПредостУслуга CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.ПредостУслуга CustomAttributes)
        public virtual IIS.Itog3.Услуга ПредостУслуга
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.ПредостУслуга Get start)

                // *** End programmer edit section *** (ОказУслуг.ПредостУслуга Get start)
                IIS.Itog3.Услуга result = this.fПредостУслуга;
                // *** Start programmer edit section *** (ОказУслуг.ПредостУслуга Get end)

                // *** End programmer edit section *** (ОказУслуг.ПредостУслуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.ПредостУслуга Set start)

                // *** End programmer edit section *** (ОказУслуг.ПредостУслуга Set start)
                this.fПредостУслуга = value;
                // *** Start programmer edit section *** (ОказУслуг.ПредостУслуга Set end)

                // *** End programmer edit section *** (ОказУслуг.ПредостУслуга Set end)
            }
        }
        
        /// <summary>
        /// Оказ услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.Договор CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.Договор CustomAttributes)
        [PropertyStorage(new string[] {
                "Договор"})]
        [NotNull()]
        public virtual IIS.Itog3.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.Договор Get start)

                // *** End programmer edit section *** (ОказУслуг.Договор Get start)
                IIS.Itog3.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (ОказУслуг.Договор Get end)

                // *** End programmer edit section *** (ОказУслуг.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.Договор Set start)

                // *** End programmer edit section *** (ОказУслуг.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (ОказУслуг.Договор Set end)

                // *** End programmer edit section *** (ОказУслуг.Договор Set end)
            }
        }
        
        /// <summary>
        /// Оказ услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.ПереченьУслуг CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.ПереченьУслуг CustomAttributes)
        [PropertyStorage(new string[] {
                "ПереченьУслуг"})]
        [NotNull()]
        public virtual IIS.Itog3.ПереченьУслуг ПереченьУслуг
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.ПереченьУслуг Get start)

                // *** End programmer edit section *** (ОказУслуг.ПереченьУслуг Get start)
                IIS.Itog3.ПереченьУслуг result = this.fПереченьУслуг;
                // *** Start programmer edit section *** (ОказУслуг.ПереченьУслуг Get end)

                // *** End programmer edit section *** (ОказУслуг.ПереченьУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.ПереченьУслуг Set start)

                // *** End programmer edit section *** (ОказУслуг.ПереченьУслуг Set start)
                this.fПереченьУслуг = value;
                // *** Start programmer edit section *** (ОказУслуг.ПереченьУслуг Set end)

                // *** End programmer edit section *** (ОказУслуг.ПереченьУслуг Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Itog3.РасчетОстВрем.
        /// </summary>
        // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем CustomAttributes)

        // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетОстВрем"})]
        public virtual IIS.Itog3.РасчетОстВрем РасчетОстВрем
        {
            get
            {
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Get start)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Get start)
                IIS.Itog3.РасчетОстВрем result = this.fРасчетОстВрем;
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Get end)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Set start)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Set start)
                this.fРасчетОстВрем = value;
                // *** Start programmer edit section *** (ОказУслуг.РасчетОстВрем Set end)

                // *** End programmer edit section *** (ОказУслуг.РасчетОстВрем Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказУслугE", typeof(IIS.Itog3.ОказУслуг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказУслуг CustomAttributes)
    public class DetailArrayOfОказУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Itog3.DetailArrayOfОказУслуг members)

        // *** End programmer edit section *** (IIS.Itog3.DetailArrayOfОказУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказУслуг.
        /// </summary>
        public DetailArrayOfОказУслуг(IIS.Itog3.РасчетОстВрем fРасчетОстВрем) : 
                base(typeof(ОказУслуг), ((ICSSoft.STORMNET.DataObject)(fРасчетОстВрем)))
        {
        }
        
        public IIS.Itog3.ОказУслуг this[int index]
        {
            get
            {
                return ((IIS.Itog3.ОказУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Itog3.ОказУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
